{{- if .Values.bullmqUI.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nx-mono-infrastructure.fullname" . }}-bullmq-ui
  labels:
    {{- include "nx-mono-infrastructure.labels" . | nindent 4 }}
    app.kubernetes.io/component: bullmq-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nx-mono-infrastructure.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: bullmq-ui
  template:
    metadata:
      labels:
        {{- include "nx-mono-infrastructure.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: bullmq-ui
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: bullmq-ui
          image: "{{ .Values.bullmqUI.image.repository }}:{{ .Values.bullmqUI.image.tag }}"
          imagePullPolicy: {{ .Values.bullmqUI.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.bullmqUI.service.targetPort }}
              protocol: TCP
          env:
            - name: REDIS_HOST
              value: "{{ include "nx-mono-infrastructure.fullname" . }}-redis-master"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: ""
            - name: REDIS_USE_TLS
              value: "false"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.bullmqUI.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nx-mono-infrastructure.fullname" . }}-bullmq-ui
  labels:
    {{- include "nx-mono-infrastructure.labels" . | nindent 4 }}
    app.kubernetes.io/component: bullmq-ui
spec:
  type: {{ .Values.bullmqUI.service.type }}
  ports:
    - port: {{ .Values.bullmqUI.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nx-mono-infrastructure.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: bullmq-ui
{{- end }}
