apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    component: backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    component: backend
rules:
  - apiGroups: ['']
    resources: ['configmaps', 'secrets']
    verbs: ['get', 'list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    component: backend
subjects:
  - kind: ServiceAccount
    name: api-gateway
    namespace: default
roleRef:
  kind: Role
  name: api-gateway
  apiGroup: rbac.authorization.k8s.io
